### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by joraco-dev** [joraco-dev/prometeo#2]
State tha hardware used

**Comment by joraco-dev** [comment]
This is the hardware used on the project. I used Amazon.com to search for the devices. There is no commercial purpose on this

https://www.amazon.com/AZDelivery-Nodemcu-Module-ESP8266-Development/dp/B07F61FG7V/ref=sr_1_7?keywords=azdelivery+esp8266&qid=1568908693&s=gateway&sr=8-7
https://www.amazon.com/HiLetgo-Temperature-Humidity-Digital-3-3V-5V/dp/B01DKC2GQ0/ref=sr_1_4?keywords=dht11&qid=1568908772&s=gateway&sr=8-4
https://www.amazon.com/HiLetgo-Sensor-Methane-Detection-Arduino/dp/B00LODGQCS/ref=sr_1_1?keywords=smoke+sensor+mq&qid=1568908820&s=gateway&sr=8-1

**Comment by derekteay** [comment]
Per @joraco-dev, this board should also work - https://www.amazon.com/gp/product/B010O1G1ES/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1

Ordered mine and will confirm on Monday. Chose this board because it was available on Prime and would show up next day, unlike the first board
